language: go
go:
- 1.5
before_script:
- pushd js2
- npm version
- nvm install stable
- nvm use stable
- npm version
- npm install
- npm build
- npm test
- popd
script:
- export GODEBUG=invalidptr=0
- go test ./...
notifications:
  email:
    recipients:
      - aa@attic.io # has email rules to filter out PRs then forward to slack
    on_failure: always
    on_success: change
    on_start: never
