language: go
go:
- 1.5
before_install:
- npm version
- nvm install stable
- nvm use stable
- npm version
install: true # no need to do the default install
before_script:
- pushd js
- npm install
- npm test
- popd
- pushd clients/splore
- ./build.py
- npm test
- popd
- pushd clients/pitchmap/ui
- ./build.py
- npm test
- popd
- pushd clients/crunchbase/ui
- ./build.py
- npm test
- popd
script:
- export GODEBUG=invalidptr=0
- go test ./...
notifications:
  email:
    recipients:
      - aa@attic.io # has email rules to filter out PRs then forward to slack
    on_failure: always
    on_success: change
    on_start: never
caches:
  directories:
  - js/node_modules
  - clients/crunchbase/ui/node_modules
  - clients/pitchmap/ui/node_modules
  - clients/splore/node_modules
  - clients/tagshow/node_modules
