language: go
go:
- 1.5
before_install:
- npm version
- nvm install stable
- nvm use stable
- npm version
install: true # no need to do the default install
before_script:
- npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
- npm whoami
- pushd js
- npm prune
- npm install
- npm test
- popd
- pushd clients/splore
- npm prune
- ./build.py
- npm test
- popd
- pushd nomdl/codegen/test
- npm prune
- npm install
- npm test
- popd
script:
- export GODEBUG=invalidptr=0
- export GO15VENDOREXPERIMENT=1
- go test `go list ./... | grep -v vendor`
notifications:
  email:
    recipients:
    - aa@attic.io # has email rules to filter out PRs then forward to slack
    on_failure: always
    on_success: change
    on_start: never
cache:
  directories:
  - js/node_modules
  - clients/splore/node_modules
  - nomdl/codegen/test/node_modules
deploy:
  provider: script
  script: tools/publish-js-sdk.py
  on:
    branch: master
