on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Dolt Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        # GITHUB_REF is expected to be set in the format refs/tags/0.3.1
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: dolt
          homebrew-tap: Homebrew/homebrew-core
          base-branch: release
          download-url: ${{format('https://github.com/liquidata-inc/dolt/archive/v{0}.tar.gz', steps.get_version.outputs.VERSION)}}
          commit-message: ${{format('dolt {0}', steps.get_version.outputs.VERSION)}}
        env:
          COMMITTER_TOKEN: ${{secrets.HOMEBREW_GITHUB_TOKEN}}
