name: Release Notification

on: release

jobs:
  notify:
    name: Release Notification
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notify
        if: always()
#        uses: dolthub/ga-discord-notify@master
        with:
          job-status: ${{ job.status }}
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          notify-on-success: true
