name: Test Benchmark Runner Utility Works

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
      - 'integration-tests/**'

concurrency:
  group: ci-benchmark-runner-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark_runner:
    runs-on: ubuntu-22.04
    name: Test Benchmark Runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Dockerfile
        run: cp -r ./go/performance/continuous_integration/. .
# TODO: fix this before rerunning
#      - name: Test runner
#        uses: ./.github/actions/benchmark-runner-tests
