name: Benchmark Latency

on:
  repository_dispatch:
    types: [ benchmark-latency ]

jobs:
  performance:
    runs-on: ubuntu-22.04
    name: Benchmark Performance
    strategy:
      matrix:
        dolt_fmt: [ "__DOLT__" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.23.6'
      - name: Install aws-iam-authenticator
        run: |
          curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.8/2020-09-18/bin/linux/amd64/aws-iam-authenticator && \
          chmod +x ./aws-iam-authenticator && \
          sudo cp ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
          aws-iam-authenticator version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Create and Auth kubeconfig
        run: |
          echo "$CONFIG" > kubeconfig
          KUBECONFIG=kubeconfig kubectl config set-credentials github-actions-dolt --exec-api-version=client.authentication.k8s.io/v1alpha1 --exec-command=aws-iam-authenticator --exec-arg=token --exec-arg=-i --exec-arg=eks-cluster-1
          KUBECONFIG=kubeconfig kubectl config set-context github-actions-dolt-context --cluster=eks-cluster-1 --user=github-actions-dolt --namespace=performance-benchmarking
          KUBECONFIG=kubeconfig kubectl config use-context github-actions-dolt-context
        env:
          CONFIG: ${{ secrets.CORP_KUBECONFIG }}
      - name: Create Sysbench Performance Benchmarking K8s Job
        run: ./.github/scripts/performance-benchmarking/run-benchmarks.sh
        env:
          FROM_SERVER: ${{ github.event.client_payload.from_server }}
          FROM_VERSION: ${{ github.event.client_payload.from_version }}
          TO_SERVER: ${{ github.event.client_payload.to_server }}
          TO_VERSION: ${{ github.event.client_payload.to_version }}
          TO_PROFILE_KEY: ${{ github.event.client_payload.to_profile_key }}
          MODE: ${{ github.event.client_payload.mode }}
          ISSUE_NUMBER: ${{ github.event.client_payload.issue_number }}
          ACTOR: ${{ github.event.client_payload.actor }}
          ACTOR_EMAIL: ${{ github.event.client_payload.actor_email }}
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          KUBECONFIG: "./kubeconfig"
          INIT_BIG_REPO: ${{ github.event.client_payload.init_big_repo }}
          NOMS_BIN_FORMAT: ${{ matrix.dolt_fmt }}
          SYSBENCH_TEST_TIME: ${{ github.event.client_payload.sysbench_test_time }}
          TEMPLATE_SCRIPT: ${{ github.event.client_payload.template_script }}
      - name: Create TPCC Performance Benchmarking K8s Job
        run: ./.github/scripts/performance-benchmarking/run-benchmarks.sh
        env:
          FROM_SERVER: ${{ github.event.client_payload.from_server }}
          FROM_VERSION: ${{ github.event.client_payload.from_version }}
          TO_SERVER: ${{ github.event.client_payload.to_server }}
          TO_VERSION: ${{ github.event.client_payload.to_version }}
          MODE: ${{ github.event.client_payload.mode }}
          ISSUE_NUMBER: ${{ github.event.client_payload.issue_number }}
          ACTOR: ${{ github.event.client_payload.actor }}
          ACTOR_EMAIL: ${{ github.event.client_payload.actor_email }}
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          KUBECONFIG: "./kubeconfig"
          INIT_BIG_REPO: ${{ github.event.client_payload.init_big_repo }}
          NOMS_BIN_FORMAT: ${{ matrix.dolt_fmt }}
          WITH_TPCC: "true"
          TEMPLATE_SCRIPT: ${{ github.event.client_payload.template_script }}
